name: real_beez
description: Real Beez – End-to-end real estate services homepage (Flutter)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP & JSON
  dio: ^5.1.2

  # UI
  intl: ^0.18.1
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  badges: ^3.1.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  firebase_auth_web: 5.7.4
