name: chat_demo
description: Demo chat app (Customer / Vendor) using Bloc + MVVM
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP & JSON
  dio: ^5.1.2

  # Socket.io client
  socket_io_client: ^2.0.0

  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Persistence
  shared_preferences: ^2.1.1

  # UI
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
